### ISSUE TITLE
与RTOS和编程语言的合作？

### ISSUE THREAD

**Issue by overheat** [ARM-software/EndpointAI#10]
arm-2d有与流行的RTOS绑定的example吗？

另外可否用rust开发上层的应用交互？

**Comment by GorgonMeducer** [comment]
在 example/[template][cmsis-rtos2][pfb] 里就有例子，跟RTOS相关的内容都在 main.c 里。
只要有适合的底层适配，用Rust 开发上层应用交互是顺理成章的事情。
