### ISSUE TITLE
Arm-2D arm_2d_tile_t.phwBuffer如何对接片外spi flash中的图片数据

### ISSUE THREAD

**Issue by yanmowudi** [ARM-software/EndpointAI#8]
如果MCU片内flash太小，只能把图片bitmap放入外部spi flash存储。请问如何对接arm_2d_tile_t.phwBuffer，谢谢。

**Comment by GorgonMeducer** [comment]
目前有两个办法：

1. 选择一个有XIP的芯片：有一些芯片支持将片外的Flash通过QSPI的方式直接映射到4G地址空间里。换句话说，这类芯片允许我们通过访问指定的地址区域来直接读取片外Flash里的内容——仿佛这些内容就在片内一样。对于这类芯片，arm-2d使用的时候没有任何特别的限制。
2. 如果的芯片没有XIP，则你可能要消耗一部分RAM来中转下，效率虽然低下……但也是没办法的事情了。

**Comment by yanmowudi** [comment]
谢谢

**Comment by GorgonMeducer** [comment]
> 谢谢

请问您所使用的芯片有XIP么？

**Comment by yanmowudi** [comment]
我使用的没有XIP功能> > 谢谢
> 
> 
> 
> 请问您所使用的芯片有XIP么？

**Comment by GorgonMeducer** [comment]
非常抱歉了……
